---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: rsdemo
  namespace: mongodb

spec:
  members: 3
  version: 4.0.6
  project: opsmanager-config
  credentials: mongo-cloud-mgr
  type: ReplicaSet
  persistent: true